[package]
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
name = "iod-error-spam"
version = "0.1.0"

[dependencies]
env_logger = "0.4.3"
log = "0.3.8"
rumqtt = "0.10.0"
serde = "1.0.12"
serde_derive = "1.0.12"
serde_json = "1.0.3"
